<?php /* Smarty version 3.1.27, created on 2021-12-06 10:18:49
         compiled from "/home1/paul/public_html/plantillas/new/plantilla_7/application/views/web/pagina/home.tpl" */ ?>
<?php
/*%%SmartyHeaderCode:136061618661ae37e9d19f43_35261622%%*/
if(!defined('SMARTY_DIR')) exit('no direct access allowed');
$_valid = $_smarty_tpl->decodeProperties(array (
  'file_dependency' => 
  array (
    '5411063eb9914562babe793f9bd12114741556b7' => 
    array (
      0 => '/home1/paul/public_html/plantillas/new/plantilla_7/application/views/web/pagina/home.tpl',
      1 => 1539730702,
      2 => 'file',
    ),
  ),
  'nocache_hash' => '136061618661ae37e9d19f43_35261622',
  'variables' => 
  array (
    'base_url' => 0,
  ),
  'has_nocache_code' => false,
  'version' => '3.1.27',
  'unifunc' => 'content_61ae37e9d3d963_85861727',
),false);
/*/%%SmartyHeaderCode%%*/
if ($_valid && !is_callable('content_61ae37e9d3d963_85861727')) {
function content_61ae37e9d3d963_85861727 ($_smarty_tpl) {

$_smarty_tpl->properties['nocache_hash'] = '136061618661ae37e9d19f43_35261622';
?>
<section><div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel"><ol class="carousel-indicators"><li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li><li data-target="#carouselExampleIndicators" data-slide-to="1"></li><li data-target="#carouselExampleIndicators" data-slide-to="2"></li></ol><div class="carousel-inner"><div class="carousel-item active"><img src="<?php echo $_smarty_tpl->tpl_vars['base_url']->value;?>
public/img/slider/slider1.jpg" alt=""></div><div class="carousel-item"><img src="<?php echo $_smarty_tpl->tpl_vars['base_url']->value;?>
public/img/slider/slider1.jpg" alt=""></div><div class="carousel-item"><img src="<?php echo $_smarty_tpl->tpl_vars['base_url']->value;?>
public/img/slider/slider1.jpg" alt=""></div></div><a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev"><span class="icon-wrap"></span></a><a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next"><span class="icon-wrap"></span></a></div></section><section class="sect_banner_contacto"><div class="container"><div class="row align-items-center"><div class="col-lg-9"><div class="box_mensaje"><h4>OBTENGA SU NATURAL</h4><h6>Complemento con la más poderosa fórmula todo en uno</h6></div></div><div class="col-lg-3"><div class="btn_banner"><a href="<?php echo $_smarty_tpl->tpl_vars['base_url']->value;?>
contacto" class="btn_contactanos">CONTÁCTANOS</a></div></div></div></div></section><section class="sect_title_servicios" style="background: #fff;padding-bottom: 0;"><div class="container"><div class="row"><div class="col-lg-12"><div class="title_servicios"><h2>NUESTROS <span>PRODUCTOS</span></h2><p>El cuerpo humano extrae de los alimentos los nutrientes para transformarlos en sustancias vitales, si bien no en todas las ocasiones lo hará de manera óptima o en las proporciones adecuadas.</p><a href="<?php echo $_smarty_tpl->tpl_vars['base_url']->value;?>
productos" class="more_products">Ver más productos</a></div></div></div></div></section><section class="sect_productos"><div class="container"><div class="row"><div class="col-lg-12"><div class="owl-carousel productos owl-theme"><div class="item"><div class="box_item"><div class="box_head"><a href="#"><img src="<?php echo $_smarty_tpl->tpl_vars['base_url']->value;?>
public/img/productos/producto1.jpg" width="100%"></a><div class="stars"><span></span><span></span><span></span><span></span></div></div><div class="box_body"><h5><a href="#">Vega One</a></h5><h6>S/ 320.00</h6></div></div></div><div class="item"><div class="box_item"><div class="box_head"><a href="#"><img src="<?php echo $_smarty_tpl->tpl_vars['base_url']->value;?>
public/img/productos/producto3.jpg" width="100%"></a><div class="stars"><span></span><span></span><span></span><span></span></div></div><div class="box_body"><h5><a href="#">Vega One</a></h5><h6>S/ 320.00</h6></div></div></div><div class="item"><div class="box_item"><div class="box_head"><a href="#"><img src="<?php echo $_smarty_tpl->tpl_vars['base_url']->value;?>
public/img/productos/producto2.jpg" width="100%"></a><div class="stars"><span></span><span></span><span></span><span></span></div></div><div class="box_body"><h5><a href="#">Vega One</a></h5><h6>S/ 320.00</h6></div></div></div><div class="item"><div class="box_item"><div class="box_head"><a href="#"><img src="<?php echo $_smarty_tpl->tpl_vars['base_url']->value;?>
public/img/productos/producto4.jpg" width="100%"></a><div class="stars"><span></span><span></span><span></span><span></span></div></div><div class="box_body"><h5><a href="#">Vega One</a></h5><h6>S/ 320.00</h6></div></div></div></div></div></div></div></section><section class="sect_title_servicios"><div class="container"><div class="row"><div class="col-lg-12"><div class="title_servicios"><h2>LO QUE NECESITAS <span>SABER</span></h2><p>El cuerpo humano extrae de los alimentos los nutrientes para transformarlos en sustancias vitales, si bien no en todas las ocasiones lo hará de manera óptima o en las proporciones adecuadas.</p><a href="<?php echo $_smarty_tpl->tpl_vars['base_url']->value;?>
productos" class="more_products">Nuevos productos</a></div></div></div></div></section><section class="sect_servicios"><div class="container"><div class="row"><div class="col-lg-12"><div class="responsive"><!-- Nav tabs --><ul class="nav nav-tabs list_servicios"><li class="nav-item"><a class="active" data-toggle="tab" href="#corazon"><div><img src="<?php echo $_smarty_tpl->tpl_vars['base_url']->value;?>
public/img/iconos/heart.svg"></div><h5>Corazón</h5></a></li><li class="nav-item"><a class="" data-toggle="tab" href="#caloria"><div><img src="<?php echo $_smarty_tpl->tpl_vars['base_url']->value;?>
public/img/iconos/apple.svg"></div><h5>Calorías</h5></a></li><li class="nav-item"><a class="" data-toggle="tab" href="#energia"><div><img src="<?php echo $_smarty_tpl->tpl_vars['base_url']->value;?>
public/img/iconos/renewable-energy.svg"></div><h5>Energía</h5></a></li><li class="nav-item"><a class="" data-toggle="tab" href="#vitamina"><div><img src="<?php echo $_smarty_tpl->tpl_vars['base_url']->value;?>
public/img/iconos/vitamins.svg"></div><h5>Vitaminas</h5></a></li><li class="nav-item"><a class="" data-toggle="tab" href="#proteina"><div><img src="<?php echo $_smarty_tpl->tpl_vars['base_url']->value;?>
public/img/iconos/steak.svg"></div><h5>Proteínas</h5></a></li><li class="nav-item"><a class="" data-toggle="tab" href="#creatina"><div><img src="<?php echo $_smarty_tpl->tpl_vars['base_url']->value;?>
public/img/iconos/creatine.svg"></div><h5>Creatina</h5></a></li></ul></div><!-- Tab panes --><div class="tab-content tabs_services"><div class="tab-pane active" id="corazon"><div class="flex_service"><div class="flex_left"><img src="<?php echo $_smarty_tpl->tpl_vars['base_url']->value;?>
public/img/servicios/corazon.jpg" width="100%"></div><div class="flex_right"><div><span>Aumenta las pulsaciones (la frecuencia cardiaca)</span><h2>SALUD Y DEPORTE</h2><p>El corazón proporciona a través de la sangre los nutrientes y oxígeno al resto del cuerpo. Cuando nos movemos los músculos de nuestro organismo necesitan más sangre ya que requieren más nutrientes y más oxígeno. El corazón el que se encarga de esta función.</p><p>Depende del grado de adaptación y entrenamiento de cada uno. Durante el ejercicio no hay un límite.</p></div></div></div></div><div class="tab-pane fade" id="caloria"><div class="flex_service"><div class="flex_left"><img src="<?php echo $_smarty_tpl->tpl_vars['base_url']->value;?>
public/img/servicios/serv_heart.jpg" width="100%"></div><div class="flex_right"><div><span>Aumenta las pulsaciones (la frecuencia cardiaca)</span><h2>SALUD Y DEPORTE</h2><p>El corazón proporciona a través de la sangre los nutrientes y oxígeno al resto del cuerpo. Cuando nos movemos los músculos de nuestro organismo necesitan más sangre ya que requieren más nutrientes y más oxígeno. El corazón el que se encarga de esta función.</p><p>Depende del grado de adaptación y entrenamiento de cada uno. Durante el ejercicio no hay un límite.</p></div></div></div></div><div class="tab-pane fade" id="energia"><div class="flex_service"><div class="flex_left"><img src="<?php echo $_smarty_tpl->tpl_vars['base_url']->value;?>
public/img/servicios/serv_heart.jpg" width="100%"></div><div class="flex_right"><div><span>Aumenta las pulsaciones (la frecuencia cardiaca)</span><h2>SALUD Y DEPORTE</h2><p>El corazón proporciona a través de la sangre los nutrientes y oxígeno al resto del cuerpo. Cuando nos movemos los músculos de nuestro organismo necesitan más sangre ya que requieren más nutrientes y más oxígeno. El corazón el que se encarga de esta función.</p><p>Depende del grado de adaptación y entrenamiento de cada uno. Durante el ejercicio no hay un límite.</p></div></div></div></div><div class="tab-pane fade" id="vitamina"><div class="flex_service"><div class="flex_left"><img src="<?php echo $_smarty_tpl->tpl_vars['base_url']->value;?>
public/img/servicios/serv_heart.jpg" width="100%"></div><div class="flex_right"><div><span>Aumenta las pulsaciones (la frecuencia cardiaca)</span><h2>SALUD Y DEPORTE</h2><p>El corazón proporciona a través de la sangre los nutrientes y oxígeno al resto del cuerpo. Cuando nos movemos los músculos de nuestro organismo necesitan más sangre ya que requieren más nutrientes y más oxígeno. El corazón el que se encarga de esta función.</p><p>Depende del grado de adaptación y entrenamiento de cada uno. Durante el ejercicio no hay un límite.</p></div></div></div></div><div class="tab-pane fade" id="proteina"><div class="flex_service"><div class="flex_left"><img src="<?php echo $_smarty_tpl->tpl_vars['base_url']->value;?>
public/img/servicios/serv_heart.jpg" width="100%"></div><div class="flex_right"><div><span>Aumenta las pulsaciones (la frecuencia cardiaca)</span><h2>SALUD Y DEPORTE</h2><p>El corazón proporciona a través de la sangre los nutrientes y oxígeno al resto del cuerpo. Cuando nos movemos los músculos de nuestro organismo necesitan más sangre ya que requieren más nutrientes y más oxígeno. El corazón el que se encarga de esta función.</p><p>Depende del grado de adaptación y entrenamiento de cada uno. Durante el ejercicio no hay un límite.</p></div></div></div></div><div class="tab-pane fade" id="creatina"><div class="flex_service"><div class="flex_left"><img src="<?php echo $_smarty_tpl->tpl_vars['base_url']->value;?>
public/img/servicios/serv_heart.jpg" width="100%"></div><div class="flex_right"><div><span>Aumenta las pulsaciones (la frecuencia cardiaca)</span><h2>SALUD Y DEPORTE</h2><p>El corazón proporciona a través de la sangre los nutrientes y oxígeno al resto del cuerpo. Cuando nos movemos los músculos de nuestro organismo necesitan más sangre ya que requieren más nutrientes y más oxígeno. El corazón el que se encarga de esta función.</p><p>Depende del grado de adaptación y entrenamiento de cada uno. Durante el ejercicio no hay un límite.</p></div></div></div></div></div></div></div></div></section><section class="sect_proceso"><div class="container"><div class="row"><div class="col-lg-12"><div class="title_proceso"><h2>PROCESO DE LOS<span> SUPLEMENTOS</span></h2></div></div><div class="col-lg-12"><ul class="list_proceso"><li><img src="<?php echo $_smarty_tpl->tpl_vars['base_url']->value;?>
public/img/iconos/proceso/proceso1.svg"><h6>Quemar calorías</h6></li><li><img src="<?php echo $_smarty_tpl->tpl_vars['base_url']->value;?>
public/img/iconos/proceso/proceso2.svg"><h6>Suprime el apetito</h6></li><li><img src="<?php echo $_smarty_tpl->tpl_vars['base_url']->value;?>
public/img/iconos/proceso/proceso3.svg"><h6>Aumenta la energía</h6></li><li><img src="<?php echo $_smarty_tpl->tpl_vars['base_url']->value;?>
public/img/iconos/proceso/proceso4.svg"><h6>Vida Felíz</h6></li></ul></div></div></div></section><section class="sect_title_servicios"><div class="container"><div class="row"><div class="col-lg-12"><div class="title_servicios"><h2>TESTIMONIOS DE <span>CLIENTES</span></h2><p>El cuerpo humano extrae de los alimentos los nutrientes para transformarlos en sustancias vitales, si bien no en todas las ocasiones lo hará de manera óptima o en las proporciones adecuadas.</p><a href="#" class="more_products">Nuevos productos</a></div></div></div></div></section><section class="sect_testimonios"><div class="container"><div class="row align-items-center"><div class="col-lg-5"><img src="<?php echo $_smarty_tpl->tpl_vars['base_url']->value;?>
public/img/testimonios/img_testimonio.png" width="100%"></div><div class="col-lg-7"><div class="box_testimonio"><div class="box_head"><div class="owl-carousel testimonios owl-theme"><div class="item"><h6>Boris Estrada</h6><p>Desde el primer día me transmitió confianza, me  explicó de una manera clara y sencilla el por qué de mi falta de resultados a pesar de tener "buenos hábitos" alimenticios y hacer ejercicio.</p><p>La mayoría piensa que se debe de consultar un nutriólogo cuando se sufre obesidad; y es verdad,  pero los que hacemos ejercicio sabemos que el 80% del éxito en "el gym" depende de lo que comemos.</p></div><div class="item"><h6>Boris Estrada</h6><p>Desde el primer día me transmitió confianza, me  explicó de una manera clara y sencilla el por qué de mi falta de resultados a pesar de tener "buenos hábitos" alimenticios y hacer ejercicio.</p><p>La mayoría piensa que se debe de consultar un nutriólogo cuando se sufre obesidad; y es verdad,  pero los que hacemos ejercicio sabemos que el 80% del éxito en "el gym" depende de lo que comemos.</p></div></div></div></div><div class="box_counter"><div class="item"><h3>12</h3><p>Años de experiencia</p><hr class="hr_testi"></div><div class="item"><h3>350 +</h3><p>Proyectos entregados</p><hr class="hr_testi"></div><div class="item"><h3>45 +</h3><p>Clientes fidelizados</p><hr class="hr_testi"></div><div class="item"><h3>400 +</h3><p>Clientes Satisfechos</p><hr class="hr_testi"></div></div></div></div></div></section><section><div id="map" style="width: 100%;height: 400px;"></div></section><?php }
}
?>